### ISSUE TITLE
exception in second room examining red `@` field

### ISSUE THREAD

**Issue by smotanove** [MarxMustermann/OfMiceAndMechs#11]
If I stand on the red `@` in the second room (swampy) and click `e` to find out what the red `@` is, it dies.

```
Traceback (most recent call last):
  File "executeMe.py", line 459, in <module>
    interaction.loop.run()
  File "/home/me/mice/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/me/mice/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/me/mice/lib/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/me/mice/lib/python3.6/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/home/me/mice/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/me/mice/lib/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/me/mice/lib/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/me/mice/lib/python3.6/site-packages/urwid/main_loop.py", line 517, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/home/me/mice/lib/python3.6/site-packages/urwid/main_loop.py", line 563, in unhandled_input
    return self._unhandled_input(input)
  File "/home/me/OfMiceAndMechs/src/interaction.py", line 135, in show_or_exit
    processAllInput(commandKeyQueue)
  File "/home/me/OfMiceAndMechs/src/interaction.py", line 143, in processAllInput
    processInput(key)
  File "/home/me/OfMiceAndMechs/src/interaction.py", line 514, in processInput
    mainChar.examine(itemMarkedLast)
  File "/home/me/OfMiceAndMechs/src/characters.py", line 603, in examine
    messages.append(item.description)
AttributeError: 'NoneType' object has no attribute 'description'
```

**Comment by MarxMustermann** [comment]
thanks for the bug, report, i confirm the bug exists as described and it will be fixed in the next bugfix round.
