### ISSUE TITLE
 crash with keyerror 'a'

### ISSUE THREAD

**Issue by MarxMustermann** [MarxMustermann/OfMiceAndMechs#22]
{}
game ready press enter to startTraceback (most recent call last):
  File "executeMe.py", line 570, in <module>
    interaction.loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 823, in _loop
    alarm_callback()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 173, in cb
    callback(self, user_data)
  File "/home/user/OfMiceAndMechs/src/interaction.py", line 2966, in gameLoop
    processInput(key,charState=state,noAdvanceGame=True,char=char)
  File "/home/user/OfMiceAndMechs/src/interaction.py", line 1488, in processInput
    done = charState["submenue"].handleKey(key)
  File "/home/user/OfMiceAndMechs/src/interaction.py", line 2012, in handleKey
    self.char.inventory[self.subMenu.getSelection()].apply(self.char)
  File "/home/user/OfMiceAndMechs/src/items.py", line 2971, in apply
    self.createCommand()
  File "/home/user/OfMiceAndMechs/src/items.py", line 3024, in createCommand
    while not self.character.macroState["macros"]["a"][-counter] == "i":
KeyError: 'a'

**Comment by MarxMustermann** [comment]
this is fixed by now
