### ISSUE TITLE
Message unclear + exception on choosing yes

### ISSUE THREAD

**Issue by erikbgithub** [MarxMustermann/OfMiceAndMechs#6]
```
14:51:11:OfMiceAndMechs🍔  python3 executeMe.py
could not load gamestate. abort (y/n)?y
Traceback (most recent call last):
  File "executeMe.py", line 425, in <module>
    raise e
  File "executeMe.py", line 421, in <module>
    gameStateObj.load()
  File "/Users/ebernoth/coding/OfMiceAndMechs/src/gamestate.py", line 59, in load
    state = json.loads(rawstate)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by MarxMustermann** [comment]
thanks for the bug report, i will fix this in the next bug fixing round
